// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFrI8KVrWP13UhLSpWXPFPfq_Am2ZhWmc',
    appId: '1:1068464170703:web:6d9e1e1401892839a239ba',
    messagingSenderId: '1068464170703',
    projectId: 'wave-p2p',
    authDomain: 'wave-p2p.firebaseapp.com',
    storageBucket: 'wave-p2p.firebasestorage.app',
    measurementId: 'G-JCWJ48SF5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mgTJr51VV8_s4wG5QpnkWrne2HrCsrw',
    appId: '1:1068464170703:android:522cdd2c61ed6687a239ba',
    messagingSenderId: '1068464170703',
    projectId: 'wave-p2p',
    storageBucket: 'wave-p2p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Ej-U7IZfRht0-rgO5i-aMxt13hF4M18',
    appId: '1:1068464170703:ios:0acdea7efcfa2a41a239ba',
    messagingSenderId: '1068464170703',
    projectId: 'wave-p2p',
    storageBucket: 'wave-p2p.firebasestorage.app',
    iosBundleId: 'com.example.p2pChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Ej-U7IZfRht0-rgO5i-aMxt13hF4M18',
    appId: '1:1068464170703:ios:0acdea7efcfa2a41a239ba',
    messagingSenderId: '1068464170703',
    projectId: 'wave-p2p',
    storageBucket: 'wave-p2p.firebasestorage.app',
    iosBundleId: 'com.example.p2pChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFrI8KVrWP13UhLSpWXPFPfq_Am2ZhWmc',
    appId: '1:1068464170703:web:703544e6a71ef959a239ba',
    messagingSenderId: '1068464170703',
    projectId: 'wave-p2p',
    authDomain: 'wave-p2p.firebaseapp.com',
    storageBucket: 'wave-p2p.firebasestorage.app',
    measurementId: 'G-W08KZJ0RNQ',
  );
}
